version: "3"
services:
  php:
    user: 1000:1000
    build: ./php
    container_name: lemp-php
    working_dir: /project.io
    volumes:
      - ./src:/project.io
    networks:
      - backend

  nginx:
    image: tutum/nginx
    container_name: lemp-nginx
    working_dir: /project.io
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./src:/project.io
      - ./nginx/default:/etc/nginx/sites-available/default
      - ./nginx/default:/etc/nginx/sites-enabled/default
      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./logs/nginx-access.log:/var/log/nginx/access.log
    networks:
      - backend

  mysql:
    image: mysql:5.7
    container_name: lemp-mysql
    ports:
      - "3306:3306"
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    networks:
      backend:
        ipv4_address: 192.168.10.10

  composer:
    user: 1000:1000
    restart: 'on-failure'
    image: composer
    container_name: lemp-composer
    working_dir: /project.io
    command:
      - install
    volumes:
      - ./src:/project.io
    networks:
      - backend

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24